name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change if using a different branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are fetched

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21  # Adjust to your Go version

      - name: Verify go.mod Exists
        run: ls -la  # Debugging step

      - name: Download Dependencies
        run: go mod tidy

      - name: Build the Application
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are fetched

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build the Application
        run: go build -o app

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "systemctl stop my-go-app || true"
          scp app $SERVER_USER@$SERVER_HOST:/home/$SERVER_USER/app
          ssh $SERVER_USER@$SERVER_HOST "systemctl start my-go-app"
